;;; sm-c-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sm-c-mode.el

(autoload 'sm-c-mode "sm-c-mode" "\
C editing mode based on SMIE.

(fn)" t)
(register-definition-prefixes "sm-c-mode" '("sm-c-"))

;;; End of scraped data

(provide 'sm-c-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sm-c-mode-autoloads.el ends here
